name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26'
      - name: Test
        run: go test ./...
      - name: Build
        run: go build -o ./bin/yt-cli ./cmd/yt-cli
